### ISSUE TITLE
relative_uncertainty_normalized_period is not actually relative

### ISSUE THREAD

**Issue by equalaction** [cunybpl/changepointmodel#96]
I think there is an issue with the name, description, and possibly the usage of this function:

https://github.com/cunybpl/changepointmodel/blob/375ebf913ac503bb2e1a45a7113134f8eba9f157/changepointmodel/core/calc/uncertainties.py#L53C1-L80C84

This gives the absolute uncertainty of the period in question, not the relative uncertainty. To find the relative uncertainty of normalized savings, you need to find the absolute uncertainty of both the baseline and reporting period, combine them by taking the square root of the sum of the squares (which gives the absolute uncertainty of the savings) and then divide that by the savings. 

Perhaps this is already the way that the calculation of relative uncertainty for normalized savings is being handled, but I think that should be checked and the name of the function should be changed to avoid confusion in the future

Also, in the docstring, it says this is modified from Eq B-28 of ASHRAE Guideline 14. It would be more clear to say it is modified from Eq B-34.

**Comment by bsnacks000** [comment]
This is more of a question of methodology for @krysh1

**Comment by krysh1** [comment]
This one we need to hunt down in the code, but you'll notice it states that function is called twice for normalized savings. The actual relative uncertainty is calculated based on the results of those two calcs, but let's find where it happens and make sure it's correct. We never return absolute uncertainty, so the function naming is not technically incorrect because it feeds into the final calculation, but I take your point about clarity. We can update the comments to reflect appropriate eq.

**Comment by equalaction** [comment]
Thanks @krysh1. Yeah, I saw in the docstring that is says to apply it twice, but I wanted to make sure. And I hear you that the naming doesn't matter for our current purposes. However, there may be applications in the future where we do want absolute normalized uncertainty, and since we are already calculating it, I thought it would be good to have it properly named so it can be used and not abused.

**Comment by bsnacks000** [comment]
@equalaction @krysh1 The docstring I believe is referencing this function which calls it twice the way you described above...
https://github.com/cunybpl/changepointmodel/blob/development/changepointmodel/core/calc/savings.py#L57 

This in turn is the "default" calculation that is found in the savings module when you import ... https://github.com/cunybpl/changepointmodel/blob/development/changepointmodel/core/savings.py#L305

So basically if you use this high level API in `changepointmodel.core.savings` that is in there you get the default calc... It calls `weather_normalized` which is a middle ware calculation that handles the input data ultimately calls `relative_uncertainty_normalized_period` twice before doing scary stats math... This is what our server side code does in the bema app. 

if we want to add a new normalized weather calculation the easiest/safest way in the current lib would be to create a new sub class of `AbstractNormalizedSavingsCalculator` and override this hook method which i added to `3.1.2` based on our working session back in April... 
https://github.com/cunybpl/changepointmodel/blob/development/changepointmodel/core/savings.py#L97 

This would replace the call to the underlying `weather_normalized` function and you can replace it with your own business logic as long as the input to function is the same... if not then we would come up with a different class 

@peterphung2043 can help build this out ... i demo'd the updated API the other day and it is going in the new notebooks that are going to be for internal m&v use. 

So I think we are good, but we can go over it in more detail tomorrow... 

All that being said let's name things better and fix docs... apologies in that regard.. :laughing:

**Comment by krysh1** [comment]
For an intermediate function I'd rather not change the name -- we can document better to explain it, but it's not intended to be called individually --> it feeds into the final savings calc.

**Comment by bsnacks000** [comment]
I'll update docs in next patch release... prob later this week or next...
