### ISSUE TITLE
Clarity on relative savings interpretation

### ISSUE THREAD

**Issue by equalaction** [cunybpl/changepointmodel#97]
In the reporting of relative uncertainty, there is a common confusion over the meaning of the result. For example, when we report a savings like this:

Relative savings: 30%
Relative savings uncertainty: 10%

We are saying that the savings is 30% +- 3% (30%*10% = 3%). I.e. the relative savings uncertainty is uncertainty as a percentage of the savings. 

However, this can be easily confused to mean the savings is 30% +- 10%. This is the misinterpretation that the relative uncertainty is a percentage **point** value.  

We are interested in the uncertainty as a percentage of savings because this is used for our thresholds of acceptability for our savings calculations. This value should be included in the reports we write as part of our evidence that our savings calcs are valid.

However, the uncertainty in terms of percentage points is also useful and important. In reports, we should list the uncertainty of the savings in percentage points, because this is a lot more intuitive. 

I suggest creating a method that calculates the uncertainty of the savings in terms of percentage points and calling it "relative_uncertainty_percent_points". This would be useful for report writing and would be more clarifying.

**Comment by bsnacks000** [comment]
Again I think this is a methodology issue and should be discussed with @krysh1

**Comment by bsnacks000** [comment]
@equalaction That being said... the current lib allows us to create new savings calcs for notebooks by subclassing and overriding the `_savings` hook method. 

If its a matter for specific reporting then I think its best to do any extra work scaling numbers in a client application, spreadsheet or jupyter notebook and not rely on this library to directly output report schemas

**Comment by krysh1** [comment]
To be clear you want us to add:

relative_uncertainty_percent_points = relative_savings*relative_psu

?

**Comment by equalaction** [comment]
Yes @krysh1, that is my suggestion

**Comment by bsnacks000** [comment]
Ok, I see... If we are just appending a new calc at the end of the pipeline this is not a big lift... i just have to assure things are backwards compatible as much as possible.

**Comment by krysh1** [comment]
To be clear it's not as small a lift as we think -- we have people trying to use this library right now (max you included), so I think the better option would be to add this calc into the notebooks for now. In few a weeks when we have new code deployed we can come back to something like this that would necessitate schema chances.
